default: &default
    api: '61777036f4ecf11adb192f7156c6e92e'
    user: '67828456@N07'
    uri: 'https://api.flickr.com/services/rest'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default